name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install NASM and QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm qemu-system-x86

    - name: Build
      run: make

    - name: Test
      run: ./rorth.out

    - name: Clean up
      run: make c
