name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install NASM
      run: sudo apt-get install nasm

    - name: Build
      run: make

    - name: Test
      run: ./rorth.out

    - name: Clean up
      run: make c
